---
title: ""
subtitle: "Merenda Escolar"
author: "Laboratório Analytics"
layout: post
published: true
comments: true
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  screenshot.force = FALSE,
  fig.cap = '',
  fig.align = 'center',
  fig.width = 10)

options(scipen = 999)
```

```{r}
library(plotly)
library(readr)
library(tidyr)
library(plyr)
library(dplyr)
library(ggplot2)
library(leaflet)
library(knitr)
library(scales)
library(rgdal)
library(RColorBrewer)
library(rsagrespb)
```

```{r}
ideb_4ano <- read_csv("IDEB - 4º ano.csv")
ideb_9ano <- read_csv("IDEB - 9º ano.csv")
```

```{r}
utils = src_mysql('utils', group='ministerio-publico', password=NULL)

municipios = tbl(utils, 'municipio') %>%
  collect()

sagres = src_mysql('SAGRES_MUNICIPAL', group='ministerio-publico-local', password=NULL)

empenhos_merenda <- get_empenhos_filtrados(sagres, cd_funcao = 12, cd_subfuncao = 306, cd_subelemento = "02") %>%
  collect(n = Inf)

```

```{r configuracao dos mapas, results='hide'}
# Encontrado em: http://www.aesa.pb.gov.br/geoprocessamento/geoportal/shapes.html
mapa_paraiba <- readOGR("../dados/mapa_paraiba_ibge/Municipios.shp")

# Atualizando nome de municípios que mudaram de nome nos últimos anos
levels_mapa = levels(mapa_paraiba@data$Nome_Munic)
levels_mapa[51] = "Tacima"
levels_mapa[173] = "Joca Claudino"
levels_mapa[200] = "São Vicente do Seridó"
levels(mapa_paraiba@data$Nome_Munic) = levels_mapa
```


```{r}
mapa_paraiba@data$Nome_Munic = as.character(mapa_paraiba@data$Nome_Munic)
paraiba_4ano = ideb_4ano %>% 
  inner_join(mapa_paraiba@data, c('Município' = 'Nome_Munic'))

paraiba_4ano$`2015` <- cut(as.numeric(paraiba_4ano$`2015`),
                                breaks = c(3,3.5,4,4.5,5,6, 6.8),
                                include.lowest = T)

levels_mapa = mapa_paraiba@data$Nome_Munic
paraiba_municipios = data.frame(levels_mapa, mapa_paraiba@data$OBJECTID)

paraiba_municipios = paraiba_municipios %>% left_join(paraiba_4ano, c('levels_mapa' = 'Município'))

mapa_paraiba@data$Y <- paraiba_municipios$`2015`
colors = colorFactor('Blues', mapa_paraiba@data$Y)

leaflet(data = mapa_paraiba) %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  addPolygons(opacity = 0.5,
              weight = 1,
              fillColor = colors(mapa_paraiba@data$Y),
              color = 'black',
              label = paste(mapa_paraiba@data$Nome_Munic),
              popup = paste("Município: ", str_to_upper(mapa_paraiba@data$Nome_Munic), "</br>",
                            "IDEB 4º ano: ", mapa_paraiba@data$Y),
              fillOpacity = 1) %>% addLegend(position = "bottomright", pal = colors, values = mapa_paraiba@data$Y,
            title = "IDEB 4º ano por município",
            opacity = 1, na.label = "0"
  )
```

```{r}
mapa_paraiba@data$Nome_Munic = as.character(mapa_paraiba@data$Nome_Munic)
paraiba_9ano = ideb_9ano %>% 
  inner_join(mapa_paraiba@data, c('Município' = 'Nome_Munic'))
summary(as.numeric(ideb_9ano$`2015`))
paraiba_9ano$`2015` <- cut(as.numeric(paraiba_9ano$`2015`),
                                breaks = c(2, 2.5, 3, 3.5, 4, 4.5, 5, 5.4),
                                include.lowest = T)

levels_mapa = mapa_paraiba@data$Nome_Munic
paraiba_municipios = data.frame(levels_mapa, mapa_paraiba@data$OBJECTID)

paraiba_municipios = paraiba_municipios %>% left_join(paraiba_9ano, c('levels_mapa' = 'Município'))

mapa_paraiba@data$Y <- paraiba_municipios$`2015`
colors = colorFactor('Blues', mapa_paraiba@data$Y)

leaflet(data = mapa_paraiba) %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  addPolygons(opacity = 0.5,
              weight = 1,
              fillColor = colors(mapa_paraiba@data$Y),
              color = 'black',
              label = paste(mapa_paraiba@data$Nome_Munic),
              popup = paste("Município: ", str_to_upper(mapa_paraiba@data$Nome_Munic), "</br>",
                            "IDEB 4º ano: ", mapa_paraiba@data$Y),
              fillOpacity = 1) %>% addLegend(position = "bottomright", pal = colors, values = mapa_paraiba@data$Y,
            title = "IDEB 9º ano por município",
            opacity = 1, na.label = "0"
  )
```

