---
title: "Distribuição Geográfica dos Licitantes"
author: "Laboratório Analytics"
layout: post
published: false
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  screenshot.force = FALSE,
  fig.width = 10)
```

```{r}
library(dplyr)
library(leaflet)
library(stringr)
source('load-licitantes-lib.R')
```

```{r}
dados_licitantes <- read.csv("cnpjcepOk.csv", stringsAsFactors = FALSE, na.strings = '')
dados_cep <- read.csv("dados-cep.csv", stringsAsFactors = FALSE, header = TRUE, na.strings = '')

licitantes <- load_licitantes()
```

```{r}
dados_cep.selected <- dados_cep %>%
  select(c(latitude, longitude, estado, cidade))

dados_licitantes.unique <- dados_licitantes %>%
  distinct(nrcnpj, CEP)

localizacao_licitantes <- licitantes %>%
  left_join(dados_licitantes.unique, by = c('nu_CPFCNPJ' = 'nrcnpj'))

localizacao_licitantes <- localizacao_licitantes %>%
  bind_cols(dados_cep.selected)

# Endereço incorreto retornado pela API de busca
localizacao_licitantes <- localizacao_licitantes %>%
  filter(nu_CPFCNPJ != '07150557000158')
```

# Distribuição geográfica dos licitantes de merenda

```{r}
m <- leaflet() %>% setView(lng = -36.623, lat = -7.548, zoom = 4)  %>% 
  addTiles() %>%
  addMarkers(data = localizacao_licitantes,
             label = ~str_to_upper(no_Fornecedor), 
             popup = paste(
               "Nome:", str_to_upper(localizacao_licitantes$no_Fornecedor), "</br>",
               "CNPJ:", localizacao_licitantes$nu_CPFCNPJ, "</br>",
               "Local:", localizacao_licitantes$cidade, " - ", localizacao_licitantes$estado, "</br>",
               "Participações:", localizacao_licitantes$participou, "</br>",
               "Total Ganho: R$", localizacao_licitantes$total_ganho
             ))
  
m
```





