#!/bin/bash

if [ $# -eq 0 ]
  then
    echo 'Volume parameter missing.'
    echo 'Example: create-database /mnt/analytics1/volumes/database'
    exit 1
fi

echo -n 'Enter password: '
read -s password
echo

rm -fr $1

docker run \
  --name database \
  --env MYSQL_ROOT_PASSWORD=$password \
  --volume $1:/var/lib/mysql \
  --publish 3306:3306 \
  --restart=always \
  --detach mariadb

unzip 'data/*.zip' -d tmp
cd tmp

mysql -p$password < SAGRES.sql
mysql -p$password < SAGRES-keys.sql
mysql -p$password < SAGRES-novo.sql
mysql -p$password < utils.sql
mysql -p$password < notas_fiscais.sql
mysql -p$password < empresas.sql
mysql -p$password < doadores_2002_2012.sql
mysql -p$password < lava_jato.sql

mysqlimport -p$password \
  --ignore-lines=1 \
  --fields-enclosed-by='"' \
  --fields-terminated-by=',' \
  --lines-terminated-by='\n' \
  --local utils \
    empresa.csv \
    municipio.csv \
    indicadores_escolares.csv \
    cnae.csv

mysqlimport -p$password \
  --ignore-lines=1 \
  --fields-enclosed-by='"' \
  --fields-terminated-by=',' \
  --lines-terminated-by='\n' \
  --local notas_fiscais \
    nota_fiscal.csv \
    ncm.csv \
    medicamentos_nota_fiscal.csv

mysqlimport -p$password \
  --ignore-lines=1 \
  --fields-enclosed-by='"' \
  --fields-terminated-by=',' \
  --lines-terminated-by='\n' \
  --local empresas \
    cnpj_pb.csv

mysqlimport -p$password \
  --ignore-lines=1 \
  --fields-enclosed-by='"' \
  --fields-terminated-by=',' \
  --lines-terminated-by='\n' \
  --local lava_jato \
    atuacao_fornecedores_ncm.csv \
    atuacao_fornecedores_compradores.csv \
    preco_maximo_ncm_atipico.csv \
    faturamento_empresas.csv \
    metricas_2016.csv


cd ..
rm -r tmp
