---
title: "Realinhamento de Preços"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggthemes)
library(corrplot)
library(ggplot2)

library(tidyr)
library(plyr)
library(dplyr)

library(rgdal)
library(scales)


library(knitr)
```


```{r instancia tabelas do bd}

sagres = src_mysql('sagres', group='ministerio-publico', password=NULL)
utils = src_mysql('utils', group='ministerio-publico', password=NULL)

query <- sql('
  SELECT *
  FROM licitacao
  WHERE de_Obs REGEXP "merenda"
  AND dt_Ano BETWEEN 2011 AND 2015
')

licitacoes <- tbl(sagres, query) %>%
  compute(name = 'lm') %>%
  collect()

query <- sql('
  SELECT c.*
  FROM contratos c
  INNER JOIN lm
  USING (cd_UGestora, nu_Licitacao, tp_Licitacao)
')

contratos <- tbl(sagres, query) %>%
  collect()

query <- sql('
  SELECT e.*
  FROM empenhos e, lm
  WHERE e.nu_Licitacao = lm.nu_Licitacao AND
  e.cd_UGestora = lm.cd_UGestora AND
  e.tp_Licitacao = lm.tp_Licitacao AND 
  e.dt_Ano = 2015
')

empenhos_2015 <- tbl(sagres, query) %>%
  compute(name = 'em15') %>%
  collect()

query <- sql('
  SELECT e.*
  FROM empenhos e, lm
  WHERE e.nu_Licitacao = lm.nu_Licitacao AND
  e.cd_UGestora = lm.cd_UGestora AND
  e.tp_Licitacao = lm.tp_Licitacao AND 
  e.dt_Ano = 2014
')

empenhos_2014 <- tbl(sagres, query) %>%
  compute(name = 'em14') %>%
  collect()

query <- sql('
  SELECT e.*
  FROM empenhos e, lm
  WHERE e.nu_Licitacao = lm.nu_Licitacao AND
  e.cd_UGestora = lm.cd_UGestora AND
  e.tp_Licitacao = lm.tp_Licitacao AND 
  e.dt_Ano = 2013
')

empenhos_2013 <- tbl(sagres, query) %>%
  compute(name = 'em13') %>%
  collect()

query <- sql('
  SELECT e.*
  FROM empenhos e, lm
  WHERE e.nu_Licitacao = lm.nu_Licitacao AND
  e.cd_UGestora = lm.cd_UGestora AND
  e.tp_Licitacao = lm.tp_Licitacao AND 
  e.dt_Ano = 2012
')

empenhos_2012 <- tbl(sagres, query) %>%
  compute(name = 'em12') %>%
  collect()

query <- sql('
  SELECT e.*
  FROM empenhos e, lm
  WHERE e.nu_Licitacao = lm.nu_Licitacao AND
  e.cd_UGestora = lm.cd_UGestora AND
  e.tp_Licitacao = lm.tp_Licitacao AND 
  e.dt_Ano = 2011
')

empenhos_2011 <- tbl(sagres, query) %>%
  compute(name = 'em11') %>%
  collect()

empenhos <- rbind(empenhos_2011, empenhos_2012, empenhos_2013, empenhos_2014, empenhos_2015)

query <- sql('
  SELECT l.*
  FROM liquidacao l, em11 e
  WHERE l.nu_Empenho = e.nu_Empenho AND
        l.cd_UGestora = e.cd_UGestora AND
        l.dt_Ano = e.dt_Ano AND
        l.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
  ')

liquidacao_2011 <- tbl(sagres, query) %>%
  compute(name = 'liq11') %>%
  collect()

query <- sql('
  SELECT l.*
  FROM liquidacao l, em12 e
  WHERE l.nu_Empenho = e.nu_Empenho AND
        l.cd_UGestora = e.cd_UGestora AND
        l.dt_Ano = e.dt_Ano AND
        l.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
  ')

liquidacao_2012 <- tbl(sagres, query) %>%
  compute(name = 'liq12') %>%
  collect()

  
query <- sql('
  SELECT l.*
  FROM liquidacao l, em13 e
  WHERE l.nu_Empenho = e.nu_Empenho AND
        l.cd_UGestora = e.cd_UGestora AND
        l.dt_Ano = e.dt_Ano AND
        l.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
  ')

liquidacao_2013 <- tbl(sagres, query) %>%
  compute(name = 'liq13') %>%
  collect()


query <- sql('
  SELECT l.*
  FROM liquidacao l, em14 e
  WHERE l.nu_Empenho = e.nu_Empenho AND
        l.cd_UGestora = e.cd_UGestora AND
        l.dt_Ano = e.dt_Ano AND
        l.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
  ')

liquidacao_2014 <- tbl(sagres, query) %>%
  compute(name = 'liq14') %>%
  collect()


query <- sql('
  SELECT l.*
  FROM liquidacao l, em15 e
  WHERE l.nu_Empenho = e.nu_Empenho AND
        l.cd_UGestora = e.cd_UGestora AND
        l.dt_Ano = e.dt_Ano AND
        l.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
  ')

liquidacao_2015 <- tbl(sagres, query) %>%
  compute(name = 'liq15') %>%
  collect()


liquidacoes <- rbind(liquidacao_2011, liquidacao_2012, liquidacao_2013, liquidacao_2014, liquidacao_2015)

query <- sql('
  SELECT p.*
  FROM pagamentos p, em15 e
  WHERE p.nu_Empenho = e.nu_Empenho AND
        p.cd_UGestora = e.cd_UGestora AND
        p.dt_Ano = e.dt_Ano AND
        p.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
        
  ')

pagamentos_2015 <- tbl(sagres, query) %>%
  compute(name = 'pg15') %>%
  collect()

query <- sql('
  SELECT p.*
  FROM pagamentos p, em14 e
  WHERE p.nu_Empenho = e.nu_Empenho AND
        p.cd_UGestora = e.cd_UGestora AND
        p.dt_Ano = e.dt_Ano AND
        p.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
        
  ')

pagamentos_2014 <- tbl(sagres, query) %>%
  compute(name = 'pg14') %>%
  collect()


query <- sql('
  SELECT p.*
  FROM pagamentos p, em13 e
  WHERE p.nu_Empenho = e.nu_Empenho AND
        p.cd_UGestora = e.cd_UGestora AND
        p.dt_Ano = e.dt_Ano AND
        p.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
        
  ')

pagamentos_2013 <- tbl(sagres, query) %>%
  compute(name = 'pg13') %>%
  collect()

query <- sql('
  SELECT p.*
  FROM pagamentos p, em12 e
  WHERE p.nu_Empenho = e.nu_Empenho AND
        p.cd_UGestora = e.cd_UGestora AND
        p.dt_Ano = e.dt_Ano AND
        p.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
        
  ')

pagamentos_2012 <- tbl(sagres, query) %>%
  compute(name = 'pg12') %>%
  collect()

query <- sql('
  SELECT p.*
  FROM pagamentos p, em11 e
  WHERE p.nu_Empenho = e.nu_Empenho AND
        p.cd_UGestora = e.cd_UGestora AND
        p.dt_Ano = e.dt_Ano AND
        p.cd_UnidOrcamentaria = e.cd_UnidOrcamentaria
        
  ')

pagamentos_2011 <- tbl(sagres, query) %>%
  compute(name = 'pg11') %>%
  collect()


pagamentos <- rbind(pagamentos_2011, pagamentos_2012, pagamentos_2013, pagamentos_2014, pagamentos_2015)
```

```{r contratos vs. empenhos}
contrXemp <- merge(empenhos, contratos, by = c('tp_Licitacao', 'nu_Licitacao', 'cd_UGestora')) %>%
  group_by(nu_Empenho) %>%
  summarise(total = n(),
            valor_contrato = sum(vl_TotalContrato),
            valor_empenho = sum(vl_Empenho)) %>%
  mutate(dif = valor_contrato - valor_empenho) %>%
  mutate(log_contrato = log10(valor_contrato)) %>%
  mutate(log_empenho = log10(valor_empenho))

ggplot(aes(x=log_contrato, y=log_empenho), data = contrXemp) +
    geom_abline(slope=1, intercept=0, color='grey') +
    geom_point() +
    scale_x_continuous(breaks=pretty_breaks(10)) +
    scale_y_continuous(breaks=pretty_breaks(10)) +
    labs(
      title = 'Valor do contrato versus valor do empenho',
      x = 'Valor do Contrato',
      y = 'Valor do Empenho') +
    theme_minimal()


empenhoSemLici <- anti_join(empenhos, licitacoes, by= c('cd_UGestora', 'nu_Licitacao', 'tp_Licitacao'))
liciSemEmpenho <- anti_join(licitacoes, empenhos, by= c('cd_UGestora', 'nu_Licitacao', 'tp_Licitacao'))


```

```{r empenhos vs. liquidações}

empXliquid <- merge(empenhos, liquidacoes, by = c('nu_Empenho', 'cd_UGestora', 'dt_Ano', 'cd_UnidOrcamentaria')) %>%
  group_by(nu_Empenho) %>%
  summarise(total = n(),
            valor_empenho = sum(vl_Empenho),
            valor_liquidacao = sum(vl_Liquidacao)) %>%
  mutate(dif = valor_empenho - valor_liquidacao) %>%
  mutate(log_liquidacao = log10(valor_liquidacao)) %>%
  mutate(log_empenho = log10(valor_empenho))


ggplot(aes(x=log_empenho, y=log_liquidacao), data = empXliquid) +
    geom_abline(slope=1, intercept=0, color='grey') +
    geom_point() +
    scale_x_continuous(breaks=pretty_breaks(10)) +
    scale_y_continuous(breaks=pretty_breaks(10)) +
    labs(
      title = 'Valor do empenho versus valor da liquidação',
      x = 'Valor do Empenho',
      y = 'Valor da Liquidação') +
    theme_minimal()
```

```{r liquidacões vs. pagamentos}

liquidXpg <- merge(liquidacoes, pagamentos, by = c('nu_Empenho', 'cd_UGestora', 'dt_Ano', 'cd_UnidOrcamentaria')) %>%
  group_by(nu_Empenho) %>%
  summarize(total = n(),
            valor_liquidacao = sum(vl_Liquidacao),
            valor_pagamento = sum(vl_Pagamento)) %>%
  mutate(dif = valor_liquidacao - valor_pagamento) %>%
  mutate(log_liquidacao = log10(valor_liquidacao)) %>%
  mutate(log_pagamento = log10(valor_pagamento))
  

ggplot(aes(x=log_liquidacao, y=log_pagamento), data = liquidXpg) +
    geom_abline(slope=1, intercept=0, color='grey') +
    geom_point() +
    scale_x_continuous(breaks=pretty_breaks(10)) +
    scale_y_continuous(breaks=pretty_breaks(10)) +
    labs(
      title = 'Valor do empenho versus valor da liquidação',
      x = 'Valor da Liquidação',
      y = 'Valor do Pagamento') +
    theme_minimal()

```

