---
title: "licitacoes_comprador_merenda_pt2"
author: "Gileade, Júlio"
date: "6 de março de 2017"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE)
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

# Instancia conexão com o BD usando as configurações em ~/.my.cnf
sagres = src_mysql('sagres', group='ministerio-publico', password=NULL)

licitacoes = tbl(sagres, 'licitacao') %>%
  filter(dt_Ano >= 2010) %>%
  collect(n = Inf)
```



```{r limpeza de dados}
unidades_gestoras = tbl(sagres, 'codigo_ugestora') %>% 
  select(de_Ugestora, cd_Ugestora) %>%
  distinct() %>%
  collect()

tipos_licitacao = tbl(sagres, 'tipo_modalidade_licitacao') %>% 
  select(de_TipoLicitacao) %>%
  collect() %>%
  mutate(de_TipoLicitacao = as.character(de_TipoLicitacao))

tipos_regime = tbl(sagres, 'regimeexecucao') %>% 
  select(de_regimeExecucao) %>%
  collect() %>%
  mutate(de_regimeExecucao = as.character(de_regimeExecucao))
  
# Verificar diferenças entre arquivos aqui
licitacoes = tbl(sagres, 'licitacao') %>% 
  filter(dt_Ano >= 2010) %>% 
  collect(n = Inf) %>%
  mutate(tp_Licitacao = factor(tp_Licitacao)) %>%
  mutate(tp_Licitacao = factor(tp_Licitacao, 
                               levels = c(levels(tp_Licitacao), '14'),
                               labels = tipos_licitacao$de_TipoLicitacao)) %>%
  mutate(tp_Objeto = factor(tp_Objeto)) %>%
  mutate(tp_regimeExecucao = factor(tp_regimeExecucao)) %>%
  mutate(tp_regimeExecucao = factor(tp_regimeExecucao,
                                    levels = c('1', '2', '3', '4', '5'),
                                    labels = tipos_regime$de_regimeExecucao)) %>%
  select(-dt_Ano) %>%
  separate(dt_Homologacao, c('dt_AnoHomologacao', 'dt_MesHomologacao', 'dt_DiaHomologacao', 'dt_Hora', 'dt_Minuto', 'dt_Segundo')) %>%
  separate(dt_MesAno, c('dt_Mes', 'dt_Ano'), -5) %>%
  mutate(dt_Mes = as.integer(dt_Mes)) %>%
  mutate(dt_Ano = as.integer(dt_Ano)) %>%
  select(-c(dt_Hora, dt_Minuto, dt_Segundo, registroCGE)) %>%
  mutate(cd_UGestora_copy = cd_UGestora) %>%
  separate(cd_UGestora_copy, c('cd_UnGestora', 'cd_Município'), -4) %>%
  mutate(dt_AnoHomologacao = as.integer(dt_AnoHomologacao)) %>%
  mutate(dt_MesHomologacao = as.integer(dt_MesHomologacao)) %>%
  mutate(dt_DiaHomologacao = as.integer(dt_DiaHomologacao)) %>%
  left_join(unidades_gestoras, c('cd_UGestora' = 'cd_Ugestora')) %>%
  mutate(de_UGestora = factor(de_Ugestora)) %>%
  select(-de_Ugestora)

```

```{r removendo tabelas}
rm(tipos_licitacao)
rm(tipos_regime)
rm(unidades_gestoras)
```

```{r filtrando merendas}
licitacoes_merenda = licitacoes %>%
  filter(grepl('alimentacao[[:space:]]escolar|merenda', licitacoes$de_Obs, ignore.case = T))
```

## Que tipo de licitação é mais comum na compra de merenda?
```{r}
ggplot(aes(x = tp_Licitacao), data = licitacoes_merenda) +
  geom_bar(aes(fill = tp_Licitacao)) +
  scale_x_discrete(labels = c()) +
  labs(title = 'Quais licitações são mais comuns na compra de merenda?', 
       x = 'Tipo de licitação', y = 'Total', fill = 'Tipo de licitação')
```

## Geralmente, quantas propostas são recebidas para licitações de merenda?
```{r}
ggplot(aes(x = nu_Propostas), data = licitacoes_merenda) +
  geom_histogram(fill = 'orange', binwidth = 1) +
  labs(title = 'Total de propostas para licitações de merenda',
       x = 'Número de propostas', y = 'Total') +
  scale_x_continuous(breaks = seq(0, 50, 5))
```


```{r}
# Total de licitacoes com mais de 10 propostas
nrow(filter(licitacoes_merenda, nu_Propostas < 10))
nrow(filter(licitacoes_merenda, nu_Propostas >= 10))

ggplot(aes(x = nu_Propostas), data = licitacoes_merenda) +
  geom_histogram(fill = 'orange', binwidth = 5) +
  labs(title = 'Total de propostas para licitações de merenda',
       x = 'Número de propostas', y = 'Total') +
  scale_x_continuous(breaks = seq(0, 50, 5))
```

## Em que mês ocorrem mais licitações?
Aqui, usamos dados a partir de 2011, pois o ano de 2010 estava muito incompleto e 2016 não tem todoso os meses
```{r}
ggplot(aes(x = dt_Mes), data = filter(licitacoes_merenda, 
                                      dt_Ano > 2010 & dt_Ano < 2016 & dt_Mes != 0)) +
  geom_histogram(binwidth = 1, fill = I('#CF6360')) +
  scale_x_continuous(breaks = seq(1,12,1)) +
  labs(title = 'Total de licitações por mês entre os anos 2011 e 2015',
       x = 'Mês', y = 'Total')
```

## 



